### ISSUE TITLE
Name conflict with Microsoft’s official Fluent UI

### ISSUE THREAD

**Issue by superusercode** [fluent-org/fluent-windows#11]
See https://developer.microsoft.com/en-us/microsoft-365/blogs/ui-fabric-is-evolving-into-fluent-ui/

I think this absolutely warrants a name change in order to prevent confusion.

**Comment by chenyueban** [comment]
> See https://developer.microsoft.com/en-us/microsoft-365/blogs/ui-fabric-is-evolving-into-fluent-ui/
> 
> I think this absolutely warrants a name change in order to prevent confusion.

Thank you for your suggestion.
The name change is currently under consideration, and there is still some work to be done after the name change, it will take some time.
